CFLAGS = -O2 -fopenmp -Wall -std=c99
LDFLAGS += -lgomp

all: fib_par fib_seq_memo fib_par_memo parallel_map

fib_par:

fib_seq_memo:

fib_par_memo:

parallel_map:

clean:
	@rm -f fib_par
	@rm -f fib_seq_memo
	@rm -f fib_par_memo
	@rm -f parallel_map
	@rm -f *.o
